#global
macos_colorspace displayp3
# Nerd Fonts v2.2.2
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF Hack Nerd Font Mono

#kitty options
macos_option_as_alt yes
clear_all_shortcuts yes

#editor friendly
#font
font_size 14
font_family Hack Nerd Font Mono
map shift+cmd+equal change_font_size all +2.0
map shift+cmd+minus change_font_size all -2.0
#clipboard
map cmd+c copy_to_clipboard 
map cmd+v paste_from_clipboard
# remove word
map alt+backspace send_text all \x17
# remove line
map cmd+backspace send_text all \x15
# move to beginning
map cmd+left send_text all \x01
# move to end
map cmd+right send_text all \x05

#windows

┌──────────────┬───────────────┐
│              │               │
│              │               │
│              │               │
│              ├───────────────┤
│              │               │
│              │               │
│              │               │
│              ├───────────────┤
│              │               │
│              │               │
│              │               │
└──────────────┴───────────────┘
enabled_layouts tall:bias=50;full_size=1;mirrored=false
map cmd+enter toggle_fullscreen
map cmd+shift+enter toggle_maximized

#spawn new windows in same tab
map cmd+d launch --cwd=current
map cmd+w close_window
#window movement
map cmd+. next_window
map cmd+, previous_window
#layout position
map cmd+shift+. next_layout

#tabs
map cmd+t new_tab
map cmd+shift+w close_tab
map shift+cmd+. next_tab
map shift+cmd+, previous_tab 

map cmd+= resize_window wider
map cmd+- resize_window narrower

allow_remote_control yes





