require("bdub.lsp")

-- plugins
require("bdub.plugins")
require("bdub.treesitter")
require("bdub.gitsigns")
require("bdub.alpha")
require("bdub.nvim-tree")
require("bdub.bufferline")
require("bdub.telescope")
require("bdub.harpoon")
require("bdub.comment")
require("bdub.autocommands")
require("bdub.impatient")
require("bdub.autopairs")
require("bdub.cmp")
require("bdub.expand_region")
require("bdub.lualine")
require("bdub.project")
require("bdub.gomove")
require("bdub.toggleterm")
require("bdub.tabout")
require("bdub.maximizer")
require("bdub.indentline")
require("bdub.whichkey")

-- vim base
require("bdub.keymaps")
require("bdub.options")
require("bdub.colorscheme")
